package game

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strconv"
	"testing"
)

// fixture mirrors testdata/niburus_catalog.json (generated by cmd/harparse).
type fixture struct {
	Structures []fixtureItem `json:"structures"`
	Techs      []fixtureItem `json:"techs"`
	Ships      []fixtureItem `json:"ships"`
	Defenses   []fixtureItem `json:"defenses"`
}

type fixtureItem struct {
	Code        int    `json:"code"`
	Name        string `json:"name"`
	Level       int    `json:"level"`
	NextCost    Money  `json:"next_cost"`
	DurationSec int64  `json:"duration_seconds"`
}

type Money struct {
	Metal     int64 `json:"metal"`
	Crystal   int64 `json:"crystal"`
	Deuterium int64 `json:"deuterium"`
}

func loadFixture(t *testing.T) fixture {
	t.Helper()
	path := filepath.Join("..", "..", "testdata", "niburus_catalog.json")
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read fixture: %v", err)
	}
	var f fixture
	if err := json.Unmarshal(raw, &f); err != nil {
		t.Fatalf("parse fixture: %v", err)
	}
	return f
}

// within absorbs float64 rounding at high levels and the imprecise fit of a
// couple of server-custom items (<= 0.2% relative).
func within(got, want int64) bool {
	d := got - want
	if d < 0 {
		d = -d
	}
	tol := want / 500
	if tol < 1 {
		tol = 1
	}
	return d <= tol
}

func TestCatalogCostsMatchCapture(t *testing.T) {
	f := loadFixture(t)

	structByID := map[int]string{}
	for key, def := range Structures {
		structByID[def.ID] = key
	}
	techByID := map[int]string{}
	for key, def := range Techs {
		techByID[def.ID] = key
	}

	for _, it := range f.Structures {
		key, ok := structByID[it.Code]
		if !ok {
			t.Errorf("structure id %d (%s) missing from catalog", it.Code, it.Name)
			continue
		}
		got, _ := StructureCost(key, it.Level+1)
		if !within(got.Metal, it.NextCost.Metal) || !within(got.Crystal, it.NextCost.Crystal) || !within(got.Deuterium, it.NextCost.Deuterium) {
			t.Errorf("%s L%d cost = %+v, fixture %+v", it.Name, it.Level+1, got, it.NextCost)
		}
	}

	for _, it := range f.Techs {
		key, ok := techByID[it.Code]
		if !ok {
			t.Errorf("tech id %d (%s) missing from catalog", it.Code, it.Name)
			continue
		}
		got, _ := TechCost(key, it.Level+1)
		if !within(got.Metal, it.NextCost.Metal) || !within(got.Crystal, it.NextCost.Crystal) || !within(got.Deuterium, it.NextCost.Deuterium) {
			t.Errorf("%s L%d cost = %+v, fixture %+v", it.Name, it.Level+1, got, it.NextCost)
		}
	}

	for _, it := range append(append([]fixtureItem{}, f.Ships...), f.Defenses...) {
		// A zero next_cost means the unit was locked / not captured in the HAR
		// (e.g. Frigate 227 before it was unlocked), so there is nothing to compare.
		if it.NextCost.Metal == 0 && it.NextCost.Crystal == 0 && it.NextCost.Deuterium == 0 {
			continue
		}
		key := strconv.Itoa(it.Code)
		if _, ok := LookupUnit(key); !ok {
			t.Errorf("unit %d (%s) missing from catalog", it.Code, it.Name)
			continue
		}
		got, _ := UnitCost(key, 1)
		if got.Metal != it.NextCost.Metal || got.Crystal != it.NextCost.Crystal || got.Deuterium != it.NextCost.Deuterium {
			t.Errorf("%s cost = %+v, fixture %+v", it.Name, got, it.NextCost)
		}
	}
}

func TestStructureDurationRoughlyMatchesCapture(t *testing.T) {
	f := loadFixture(t)
	const robotics, nanite = 22, 11 // captured planet's levels
	const gameSpeed = 4000.0
	checked := 0
	for _, it := range f.Structures {
		if it.DurationSec == 0 || it.Code == 15 { // nanite factory uses a different curve
			continue
		}
		key := structByID(it.Code)
		if key == "" {
			continue
		}
		got := StructureDuration(key, it.Level+1, robotics, nanite, gameSpeed).Seconds()
		want := float64(it.DurationSec)
		// The fixture is from the officer/peaceful-buffed account, so the
		// modelled base time is expected to be up to ~1.9x longer. Only flag
		// gross (>2.5x) divergence.
		if got > want*2.5 || got < want*0.4 {
			t.Errorf("%s L%d duration = %.0fs, fixture %.0fs (>2.5x off)", it.Name, it.Level+1, got, want)
		}
		checked++
	}
	if checked == 0 {
		t.Fatal("no structure durations checked")
	}
}

func TestTechDurationMatchesCapture(t *testing.T) {
	f := loadFixture(t)
	const lab, university, gameSpeed = 24, 6, 4000.0 // captured planet's levels
	techByID := map[int]string{}
	for key, def := range Techs {
		techByID[def.ID] = key
	}
	checked := 0
	for _, it := range f.Techs {
		if it.DurationSec == 0 {
			continue
		}
		key := techByID[it.Code]
		if key == "" {
			continue
		}
		got := TechDuration(key, it.Level+1, lab, university, gameSpeed).Seconds()
		want := float64(it.DurationSec)
		if d := got - want; d > want*0.03 || d < -want*0.03 {
			t.Errorf("%s L%d duration = %.0fs, fixture %.0fs (>3%% off)", it.Name, it.Level+1, got, want)
		}
		checked++
	}
	if checked < 10 {
		t.Fatalf("only %d tech durations checked", checked)
	}
}

func TestEffectiveResearchLabLevel(t *testing.T) {
	cases := []struct {
		name       string
		local, irn int
		colonies   []int
		want       int
	}{
		{"no colonies", 24, 5, nil, 24},
		{"zero labs ignored", 24, 3, []int{0, 0, 0}, 24},
		{"irn connects highest", 10, 2, []int{5, 30, 20}, 60}, // 10 + 30 + 20
		{"irn level caps labs", 10, 1, []int{5, 30, 20}, 40},  // 10 + 30
		{"more irn than labs", 10, 9, []int{5, 30}, 45},       // 10 + 30 + 5
	}
	for _, c := range cases {
		if got := EffectiveResearchLabLevel(c.local, c.irn, c.colonies); got != c.want {
			t.Errorf("%s: got %d, want %d", c.name, got, c.want)
		}
	}
}

var structKeyByID = func() map[int]string {
	m := map[int]string{}
	for key, def := range Structures {
		m[def.ID] = key
	}
	return m
}()

func structByID(id int) string { return structKeyByID[id] }
